name: blamebot

services:
  webhook-server:
    image: ghcr.io/mosoveru/webhook-server:latest
    container_name: webhook-server
    ports:
      - "3000:3000"
    depends_on:
      - blamebot-db
    networks:
      - database
      - internet
    restart: on-failure
    env_file:
      - .env
  blamebot-db:
    image: ghcr.io/mosoveru/blamebot-db:latest
    container_name: blamebot-database
    ports:
      - "5432:5432"
    volumes:
      - blamebot_data:/var/lib/postgresql/data
    networks:
      - database
    restart: on-failure
    env_file:
      - .env
  bot:
    image: ghcr.io/mosoveru/telegram-bot:latest
    container_name: telegram-bot
    depends_on:
      - blamebot-db
    networks:
      - database
      - internet
    restart: on-failure
    env_file:
      - .env

networks:
  database:
    name: blamebot_database_network
  internet:
    name: blamebot_global_network

volumes:
  blamebot_data:
    name: blamebot_data